FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y curl

EXPOSE 8000

CMD ["fastapi", "run", "apirest.py"]